<?php

namespace AppBundle\Repository;

/**
 * AppellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppellerRepository extends \Doctrine\ORM\EntityRepository
{
}
