<?php

namespace AppBundle\Repository;

/**
 * AutoEvaluerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoEvaluerRepository extends \Doctrine\ORM\EntityRepository
{
}
