<?php

namespace AppBundle\Repository;

/**
 * CommentaireCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
