<?php

namespace AppBundle\Repository;

/**
 * CommantaireCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommantaireCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
