<?php

namespace AppBundle\Repository;

/**
 * EvaluerAvecEpreuveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluerAvecEpreuveRepository extends \Doctrine\ORM\EntityRepository
{
}
