<?php

namespace AppBundle\Repository;

/**
 * EvaluerSimplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluerSimplementRepository extends \Doctrine\ORM\EntityRepository
{
}
