<?php

namespace AppBundle\Repository;

/**
 * GroupeCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
