<?php

namespace AppBundle\Repository;

/**
 * IntervientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervientRepository extends \Doctrine\ORM\EntityRepository
{
}
