<?php

namespace AppBundle\Repository;

/**
 * LogUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
