<?php

namespace AppBundle\Repository;

/**
 * MigrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MigrationsRepository extends \Doctrine\ORM\EntityRepository
{
}
