<?php

namespace AppBundle\Repository;

/**
 * PasswordResetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetsRepository extends \Doctrine\ORM\EntityRepository
{
}
