<?php

namespace AppBundle\Repository;

/**
 * PossedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossedeRepository extends \Doctrine\ORM\EntityRepository
{
}
