<?php

namespace AppBundle\Repository;

/**
 * SuivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuivreRepository extends \Doctrine\ORM\EntityRepository
{
}
