AppBundle\Entity\CommantaireCompetence:
    type: entity
    table: commantaire_competence
    repositoryClass: AppBundle\Repository\CommantaireCompetenceRepository
    id:
        id_commentaireCompetence:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        commentaire:
            type: text
            nullable: true
        idCompetence:
            type: integer
            nullable: true
            column: id_competence
    lifecycleCallbacks: {  }
