AppBundle\Entity\CommentaireCompetence:
    type: entity
    table: commentaire_competence
    repositoryClass: AppBundle\Repository\CommentaireCompetenceRepository
    id:
        idCommentaireCompetence:
            type: integer
            id: true
            column: id_commentaireCompetence
            generator:
                strategy: AUTO
    fields:
        commentaire:
            type: text
            nullable: true
        idCompetence:
            type: integer
            nullable: true
            column: id_competence
    lifecycleCallbacks: {  }
