AppBundle\Entity\Competence:
    type: entity
    table: competence
    repositoryClass: AppBundle\Repository\CompetenceRepository
    id:
        idCompetence:
            type: integer
            id: true
            column: id_competence
            generator:
                strategy: AUTO
    fields:
        nomCompetence:
            type: string
            length: '100'
            nullable: true
            column: nom_competence
        idGroupeCompetence:
            type: integer
            nullable: true
            column: id_groupeCompetence
    lifecycleCallbacks: {  }
