AppBundle\Entity\EvaluerAvecEpreuve:
    type: entity
    table: evaluer_avec_epreuve
    repositoryClass: AppBundle\Repository\EvaluerAvecEpreuveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateEval:
            type: datetimetz
            nullable: true
            column: date_eval
        note:
            type: integer
            nullable: true
        idComptetence:
            type: integer
            column: id_comptetence
        idEpreuve:
            type: integer
            column: id_epreuve
        usersIdEleve:
            type: integer
            column: users_id_eleve
    lifecycleCallbacks: {  }
