AppBundle\Entity\PasswordResets:
    type: entity
    table: password_resets
    repositoryClass: AppBundle\Repository\PasswordResetsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        token:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
