AppBundle\Entity\Suivre:
    type: entity
    table: suivre
    repositoryClass: AppBundle\Repository\SuivreRepository
    id:
        id:
            type: integer
        idGroupe:
            type: integer
            column: id_groupe
        idMatiere:
            type: integer
            column: id_matiere
    lifecycleCallbacks: {  }
