ALTER TABLE annee CHANGE date_debut date_debut DATE DEFAULT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE intitule intitule VARCHAR(50) DEFAULT NULL;
DROP INDEX FK_appartenir_id_groupe ON appartenir;
DROP INDEX fk_appartenir_users1_idx ON appartenir;
DROP INDEX FK_appeller_id_contact ON appeller;
DROP INDEX fk_appeller_users1_idx ON appeller;
DROP INDEX fk_auto_evaluer_users1_idx ON auto_evaluer;
DROP INDEX FK_auto_evaluer_id_competence ON auto_evaluer;
ALTER TABLE auto_evaluer CHANGE id id INT NOT NULL, CHANGE date_autoEval date_autoEval DATETIME DEFAULT NULL;
DROP INDEX FK_commentaire_competence_id_competence ON commentaire_competence;
DROP INDEX FK_competence_id_groupeCompetence ON competence;
DROP INDEX FK_contenir_id_competence ON contenir;
DROP INDEX FK_contenir_id_epreuve ON contenir;
ALTER TABLE contenir CHANGE id id VARCHAR(255) NOT NULL;
DROP INDEX fk_epreuve_users1_idx ON epreuve;
ALTER TABLE epreuve CHANGE date_epreuve date_epreuve DATETIME DEFAULT NULL;
DROP INDEX FK_evaluer_avec_epreuve_id_competence ON evaluer_avec_epreuve;
DROP INDEX FK_evaluer_avec_epreuve_id_epreuve ON evaluer_avec_epreuve;
DROP INDEX fk_evaluer_avec_epreuve_users1_idx ON evaluer_avec_epreuve;
ALTER TABLE evaluer_avec_epreuve CHANGE date_eval date_eval DATETIME DEFAULT NULL;
DROP INDEX FK_evaluer_simplement_id_competence ON evaluer_simplement;
DROP INDEX fk_evaluer_simplement_users1_idx ON evaluer_simplement;
DROP INDEX fk_evaluer_simplement_users2_idx ON evaluer_simplement;
ALTER TABLE evaluer_simplement CHANGE date_EvaluerSimplement date_evaluerSimplement DATETIME DEFAULT NULL;
DROP INDEX FK_groupe_id_annee ON groupe;
DROP INDEX FK_groupe_id_diplome ON groupe;
DROP INDEX FK_groupe_competence_id_matiere ON groupe_competence;
DROP INDEX FK_intervient_id_matiere ON intervient;
DROP INDEX fk_intervient_users1_idx ON intervient;
DROP INDEX fk_user ON log_users;
ALTER TABLE log_users CHANGE visibilite visibilite INT NOT NULL;
ALTER TABLE migrations ADD id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id);
DROP INDEX password_resets_email_index ON password_resets;
DROP INDEX password_resets_token_index ON password_resets;
ALTER TABLE password_resets ADD id INT AUTO_INCREMENT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, ADD PRIMARY KEY (id);
DROP INDEX fk_possede_users1_idx ON possede;
DROP INDEX FK_possede_id_diplome ON possede;
DROP INDEX FK_suivre_id_matiere ON suivre;
DROP INDEX FK_suivre_id_groupe ON suivre;
ALTER TABLE suivre CHANGE id id INT NOT NULL;
ALTER TABLE users CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;