ALTER TABLE annee CHANGE date_debut date_debut DATE DEFAULT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE intitule intitule VARCHAR(50) DEFAULT NULL;
DROP INDEX FK_appartenir_id_groupe ON appartenir;
DROP INDEX fk_appartenir_users1_idx ON appartenir;
DROP INDEX FK_appeller_id_contact ON appeller;
DROP INDEX fk_appeller_users1_idx ON appeller;
DROP INDEX FK_commentaire_competence_id_competence ON commentaire_competence;
DROP INDEX FK_contenir_id_competence ON contenir;
DROP INDEX FK_contenir_id_epreuve ON contenir;
ALTER TABLE contenir DROP PRIMARY KEY;
ALTER TABLE contenir CHANGE id id INT AUTO_INCREMENT NOT NULL;
ALTER TABLE contenir ADD PRIMARY KEY (id);
DROP INDEX FK_evaluer_avec_epreuve_id_competence ON evaluer_avec_epreuve;
DROP INDEX FK_evaluer_avec_epreuve_id_epreuve ON evaluer_avec_epreuve;
DROP INDEX fk_evaluer_avec_epreuve_users1_idx ON evaluer_avec_epreuve;
ALTER TABLE evaluer_avec_epreuve CHANGE date_eval date_eval DATETIME DEFAULT NULL, CHANGE id_competence id_comptetence INT NOT NULL;
DROP INDEX FK_groupe_id_annee ON groupe;
DROP INDEX FK_groupe_id_diplome ON groupe;
DROP INDEX FK_groupe_competence_id_matiere ON groupe_competence;
DROP INDEX FK_intervient_id_matiere ON intervient;
DROP INDEX fk_intervient_users1_idx ON intervient;
ALTER TABLE users CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
